# yaml-language-server: $schema=https://docs.ludus.cloud/schemas/range-config.json
ludus:
  - vm_name: "DC01"
    hostname: "dc01"
    template: win2022-server-x64-template
    vlan: 10
    ip_last_octet: 1
    ram_gb: 8
    cpus: 2
    windows:
      sysprep: true
    domain:
      fqdn: e1a.local
      role: primary-dc
    roles:
      - e1a.ludus_windows_smb_share
    role_vars:
      ludus_windows_smb_share_name: 'Corporate Files'
      ludus_windows_smb_share_path: 'C:\Shares\corpfiles'
      ludus_windows_smb_share_read_group: 'E1A\Domain Users'
      ludus_windows_smb_share_write_group: 'E1A\Domain Admins'
      ludus_windows_smb_share_description: 'Corporate file share'
      ludus_windows_smb_share_list: true
      ludus_windows_smb_share_full_users: 'BUILTIN\Administrators'
      ludus_windows_smb_share_create_path: true
      ludus_windows_smb_share_set_ntfs_acl: true
      ludus_windows_smb_share_read_acl_rights: 'ReadAndExecute,Synchronize'
      ludus_windows_smb_share_write_acl_rights: 'Modify,Synchronize'

  - vm_name: "SRV01"
    hostname: "srv01"
    template: win2022-server-x64-template
    vlan: 10
    ip_last_octet: 2
    ram_gb: 8
    cpus: 2
    windows:
      sysprep: true
    domain:
      fqdn: e1a.local
      role: member
    roles:
      - e1a.ludus_windows_smb_share
    role_vars:
      ludus_windows_smb_share_name: Gabber
      ludus_windows_smb_share_path: 'C:\Shares\gabber'
      ludus_windows_smb_share_read_group: 'NT AUTHORITY\Authenticated Users'
      ludus_windows_smb_share_write_group: 'E1A\Domain Computers'
      ludus_windows_smb_share_description: 'Hakkenn'
      ludus_windows_smb_share_list: true
      ludus_windows_smb_share_full_users: 'BUILTIN\Administrators'
      ludus_windows_smb_share_create_path: true
      ludus_windows_smb_share_set_ntfs_acl: true
      ludus_windows_smb_share_read_acl_rights: 'ReadAndExecute,Synchronize'
      ludus_windows_smb_share_write_acl_rights: 'Modify,Synchronize'

  - vm_name: "WIN11"
    hostname: "win11"
    template: win11-22h2-x64-enterprise-template
    vlan: 10
    ip_last_octet: 3
    ram_gb: 8
    cpus: 2
    windows:
      sysprep: true
    domain:
      fqdn: e1a.local
      role: member
    roles:
      - e1a.ludus_windows_smb_share
    role_vars:
      ludus_windows_smb_share_name: rahhhh$
      ludus_windows_smb_share_path: 'C:\Shares\idk'
      ludus_windows_smb_share_read_group: 'E1A\Domain Users'
      ludus_windows_smb_share_write_group: 'BUILTIN\Remote Desktop Users'
      ludus_windows_smb_share_description: 'Workstation share'
      ludus_windows_smb_share_list: false
      ludus_windows_smb_share_full_users: 'BUILTIN\Administrators'
      ludus_windows_smb_share_create_path: true
      ludus_windows_smb_share_set_ntfs_acl: true
      ludus_windows_smb_share_read_acl_rights: 'ReadAndExecute,Synchronize'
      ludus_windows_smb_share_write_acl_rights: 'Modify,Synchronize'